(require 'auto-complete)
(require 'auto-complete-config)
(require 'pos-tip)
(setq ac-quick-help-pos-tip t)
(ac-config-default)
(require 'fuzzy)
(setq ac-fuzzy-enable t)
(require 'neotree)
(global-set-key [f8] 'neotree-toggle)
(provide 'init-packages-config)
